# Generated by Django 5.2.7 on 2026-04-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='communicati_convers_8ec2ee_idx'),
        ),
        migrations.AddField(
            model_name='messageseen',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='communications.message'),
        ),
        migrations.AddField(
            model_name='messageseen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messageseen',
            index=models.Index(fields=['user', 'message'], name='communicati_user_id_8ad4d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageseen',
            unique_together={('message', 'user')},
        ),
    ]
