# Generated by Django 5.1.7 on 2025-12-05 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0012_remove_attendancesession_classroom_and_more'),
        ('accounts', '0014_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st', '1st Term'), ('2nd', '2nd Term'), ('3rd', '3rd Term')], max_length=10)),
                ('overall_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('position_in_class', models.PositiveIntegerField(default=0)),
                ('teacher_remark', models.TextField(blank=True)),
                ('teacher_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('headmaster_remark', models.TextField(blank=True)),
                ('reopening_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classroom')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'session', 'term')},
            },
        ),
    ]
