# Generated by Django 5.2.7 on 2026-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='class_participation_rating',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_bad', 'Very Bad')], max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='homework_rating',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_bad', 'Very Bad')], max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='neatness_rating',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_bad', 'Very Bad')], max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='punctuality_rating',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_bad', 'Very Bad')], max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='respect_discipline_rating',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_bad', 'Very Bad')], max_length=20),
        ),
    ]
