# Generated by Django 5.1.7 on 2025-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
