# Generated by Django 5.2.7 on 2026-08-14 11:25

import django.db.models.deletion
from django.db import migrations, models


def _term_for_date(session, date):
    """Inline copy of attendance.services.get_term_for_date for migration use."""
    if not session or not session.start_date or not session.end_date:
        return ""
    total_days = (session.end_date - session.start_date).days + 1
    if total_days <= 0:
        return ""
    offset = (date - session.start_date).days
    if offset < 0:
        return "1st"
    if offset >= total_days:
        return "3rd"
    third = total_days / 3
    if offset < third:
        return "1st"
    if offset < 2 * third:
        return "2nd"
    return "3rd"


def backfill_sessions(apps, schema_editor):
    """Attribute existing attendance sessions to the active academic session/term."""
    AttendanceSession = apps.get_model("attendance", "AttendanceSession")
    Session = apps.get_model("academics", "Session")

    active_session = Session.objects.filter(is_current=True).first()
    if not active_session:
        return

    for att in AttendanceSession.objects.filter(session__isnull=True):
        att.session_id = active_session.id
        att.term = _term_for_date(active_session, att.date)
        att.save(update_fields=["session", "term"])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_remove_attendancesession_classroom_and_more'),
        ('attendance', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.session'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='term',
            field=models.CharField(blank=True, choices=[('1st', '1st Term'), ('2nd', '2nd Term'), ('3rd', '3rd Term')], max_length=10),
        ),
        migrations.RunPython(backfill_sessions, migrations.RunPython.noop),
    ]
